export const GET_EMPLOYEES_INIT = "GET_EMPLOYEES_INIT";
export const GET_EMPLOYEES_SUCCESS = "GET_EMPLOYEES_SUCCESS";
export const GET_EMPLOYEES_FAILURE = "GET_EMPLOYEES_FAILURE";


export const GET_PROFILE_INFO_INIT = "GET_PROFILE_INFO_INIT";
export const GET_PROFILE_INFO_SUCCESS = "GET_PROFILE_INFO_SUCCESS";
export const GET_PROFILE_INFO_FAILURE = "GET_PROFILE_INFO_FAILURE";

export const LOGIN_INIT = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const SUBMIT_PAYMENT_INIT = "SUBMIT_PAYMENT_INIT";
export const SUBMIT_PAYMENT_SUCCESS = "SUBMIT_PAYMENT_SUCCESS";
export const SUBMIT_PAYMENT_FAILURE = "SUBMIT_PAYMENT_FAILURE";