// variable names as export const VARIABLE_NAME = "VARIABLE_NAME"

export const GET_PROFILE_INFO_INIT = "GET_PROFILE_INFO_INIT";
export const GET_PROFILE_INFO_SUCCESS = "GET_PROFILE_INFO_SUCCESS";
export const GET_PROFILE_INFO_FAILURE = "GET_PROFILE_INFO_FAILURE";