export const GET_EMPLOYEES_INIT = "GET_EMPLOYEES_INIT";
export const GET_EMPLOYEES_SUCCESS = "GET_EMPLOYEES_SUCCESS";
export const GET_EMPLOYEES_FAILURE = "GET_EMPLOYEES_FAILURE";

export const LOGIN_INIT = "LOGIN_INIT";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT = "LOGOUT";

export const SUBMIT_PAYMENT_INIT = "SUBMIT_PAYMENT_INIT";
export const SUBMIT_PAYMENT_SUCCESS = "SUBMIT_PAYMENT_SUCCESS";
export const SUBMIT_PAYMENT_FAILURE = "SUBMIT_PAYMENT_FAILURE";

export const UPDATE_PROFILE_INFO_INIT = "UPDATE_PROFILE_INFO_INIT";
export const UPDATE_PROFILE_INFO_SUCCESS = "UPDATE_PROFILE_INFO_SUCCESS";
export const UPDATE_PROFILE_INFO_FAILURE = "UPDATE_PROFILE_INFO_FAILURE";

export const UPDATE_PHOTO_INIT = "UPDATE_PHOTO_INIT";
export const UPDATE_PHOTO_SUCCESS = "UPDATE_PHOTO_SUCCESS";
export const UPDATE_PHOTO_FAILURE = "UPDATE_PHOTO_FAILURE";

export const CREATE_PROFILE_INFO_INIT = "CREATE_PROFILE_INFO_INIT";
export const CREATE_PROFILE_INFO_SUCCESS = "CREATE_PROFILE_INFO_SUCCESS";
export const CREATE_PROFILE_INFO_FAILURE = "CREATE_PROFILE_INFO_FAILURE";

export const REGISTER_INIT = "REGISTER_INIT";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";